CREATE OR ALTER PROCEDURE spMiscDataWithFilter
--execute  spMiscDataWithFilter "CONTACTUS","DROPDOWN",1
    @PAGENAME VARCHAR(50),
    @FIELDTYPE VARCHAR(50),
    @ACTIVE bit
    
    
AS
BEGIN
   
        SELECT FIELDNAME,FIELDVALUE FROM MISCDATA WHERE PAGENAME='CONTACTUS' AND FIELDTYPE='DROPDOWN' AND ACTIVE=1
        
END;


